query GetFoodList {
    getFoodList {
        ok
        result {
            name
            calories
            proteins
            carbs
            fats
            ingredients {
                name
                calories
                proteins
                carbs
                fats
                ingredients {
                    name
                }
                givenAmount
                actualAmount
            }
            givenAmount
            actualAmount
        }
        message
    }
}
